"""Stable error codes returned by Task Management business rules."""

INVALID_PROJECT_TRANSITION = "TASKMGMT_INVALID_PROJECT_TRANSITION"
INVALID_TASK_TRANSITION = "TASKMGMT_INVALID_TASK_TRANSITION"
INVALID_TASK_HIERARCHY = "TASKMGMT_INVALID_TASK_HIERARCHY"
INCOMPLETE_CHILDREN = "TASKMGMT_INCOMPLETE_CHILDREN"
INVALID_PROJECT_MEMBER = "TASKMGMT_INVALID_PROJECT_MEMBER"
PROJECT_KEY_CONFLICT = "TASKMGMT_PROJECT_KEY_CONFLICT"
TASK_LINK_CYCLE = "TASKMGMT_TASK_LINK_CYCLE"
ATTACHMENT_LIMIT = "TASKMGMT_ATTACHMENT_LIMIT"
ATTACHMENT_TYPE = "TASKMGMT_ATTACHMENT_TYPE"
ATTACHMENT_SIZE = "TASKMGMT_ATTACHMENT_SIZE"

